# -*- coding: utf-8 -*-
"""class 120

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayBeHyPmhtputx3i0cv5quveDj-k3Yld
"""

from google.colab import files 
files.upload()

import pandas as pd
df = pd.read_csv("data120.csv")
print(df.head())

from sklearn.model_selection import train_test_split
x = df[["glucose", "bloodpressure"]]
y = df["diabetes"]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state = 1 )

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
model = GaussianNB()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
accuracy = accuracy_score(y_test, y_predict)
print(accuracy)

x = df[["glucose", "bloodpressure"]]
y = df["diabetes"]
x_train1, x_test1, y_train1, y_test1 = train_test_split(x,y,test_size = 0.25, random_state = 42 )

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
x_train1 = sc1.fit_transform(x_train1)
x_test1 = sc1.fit_transform(x_test1)
model1 = LogisticRegression()
model1.fit(x_train1, y_train1)
y_predict1 = model1.predict(x_test1)
accuracy1 = accuracy_score(y_test1, y_predict1)
print(accuracy1)